export const flavours = [
    "Rose",
    "Strawberry",
    "Cola",
    "Banana",
    "Banoffee",
    "Chocolate",
    "Vanilla",
    "Lime",
    "Coconut",
    "Carrot",
    "Coffee",
    "Green Tea",
    "Matcha",
    "Wasabi",
    "Mint",
    "Peppermint",
    "Spearmint",
    "Rosemary",
    "Chamomile",
    "Marshmallow",
    "Peanut",
];
